apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitea.local.fresh96jwjw.org/jw/homelab-infra.git
    targetRevision: main
    path: k8s/crowdsec
  destination:
    server: https://kubernetes.default.svc
    namespace: crowdsec
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
