---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-creds-image-updater
  namespace: argocd
spec:
  encryptedData:
    password: AgCnt5S0TWFWRWuVzjPjDxF6qgN1T6WcubQnwM9+H5zlE89wgaO4JcIDigobqmm1b70sm/GHS3OgXxt35jHH2KFedn1H5AvG8hdtI6emHU9F/MTd8HTp8I9Nk16KYwWgAoaGBwxOWkOkGVCLwbdyHU1lbivSEWVgp1rt8CrKCwzrJGmqrRkOORBISaj1nuyXaqJsghosKpNcEEd5+Sbny2hrpMOD10cjlTuFfG9UDpp/u58IaA6XJUDhLZkgO2boOTvZWcwqmCtFHIJ66sk9V+AX9tFjMrDw7tUqbc19+vIzCaYt1L5fcaBMU+g614itxwoQQtFpkXRCHrrbP3YzoXwbCgc3bnUApeFdZA2c+bQQVyHlb9FRC/CoYgzi7ofT/l2r3dr7paplya7P8mZ43aDBHzt0Rd58AUCh/6l05NOflKtynRw2hNpuPTHLZ8d8a4YBMf84Ju1nHtTmv6ZXom6HV265FAm7TRyATKNhl0c9hM+zthQKZboRfedyEpeoAw2nRlHzswjgM23X7b4Becqhuht08ZFYjodEqQbHPTLDIKxosgX04USrRF3SsjCQm4nayTjYpGBno/aniQItWEDOYK0Jk2h+1/AIzWSQUsSOc2po9JQGPFsPB+p98i++TvyCjmIXCAVQRxnHTyy+ZkmuJEEck/JHoX/M6NCBoyte8I5ykNDVVNXdwT8ZtRfdAzqzeXxbG5YtKuIdB1MnpK3BHebS9y6HVyA9ikMzcvMiaE5RAlihmKHO
    username: AgANB8bwitowKvpDmXcN4qndNrsM7u5Y7aDcmImM1YJjyO1MgUjiK1v4xvq0ShSOJAX/mmRFqHh1JB7R5/kYkJ0H3CYOOm/aelzjGHA+hNrO0G7WZliVa5M8njOr8yJsd1NRKTM1Qc3ZtfeGTYRkeKk+jIdAD1yxIeIOIJmM+j8QvYWk9jxooJdQPNKb4bmXBnVErbXXcA9RRHV2IXrRTqkFoB7lzeZKVoRhZzZY/QEGInhEceNWU9Rfua4tMZVI95FRVNsvrb20ZgG8XUVas2YfkBkkx8nU6FsS+FKAQoxZTum+tutnPnNUruiLFmZF1qm6bMgIglZP8scYG/7nJTVYyQ/uvnCK4Ormq11Sy/s6//3rzaq6T2wtpAvcaNjcBfah+S8GQOtCDqTGk0cZWoZwnElmObuCNZqM1FAr144NK7aa8sNzR5Y4Vzl99DsN8itD9iIiLBo4k1eh0t34Zd13pTsbB/k0IvfhScnwprR6+tZQCHP+SdvE+b+OPkKJLjLTpXVR+BkBSlXU1kA15/owl7OcGQViq020SfrjJk/CwIbOXYjMk5am0N6Ebhxvfkkcnrq6P+POWQXbdep/XHinnKYBTKzJJdbkwLdZ05VEAEhCQRy3eNFXNcHHq43Bru98AICtWJAUTqFfHGD789lNNrBcGJP886eowjTmYsSdcx14lFYzpmV6hi7yc3alhhe+vg==
  template:
    metadata:
      name: gitea-creds-image-updater
      namespace: argocd
